### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages/Hydrogen/node_modules/@nteract/mathjax/li...

### ISSUE THREAD

**Issue by lecondon** [nteract/hydrogen#1945]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.14.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.1

### Stack Trace

Uncaught Error: Cannot find module '/Users/laura/.atom/packages/Hydrogen/node_modules/@nteract/mathjax/lib/index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:248

Error: Cannot find module '/Users/laura/.atom/packages/Hydrogen/node_modules/@nteract/mathjax/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:13:30)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:30:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:6:43)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:11:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-file-icons 0.7.1 
atom-language-r 1.4.8 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
git-plus 8.7.1 
git-time-machine 2.1.0 
Hydrogen 2.14.1 
intentions 1.1.5 
kite 0.184.0 
language-fortran 2.1.10 
language-latex 1.2.0 
language-matlab 0.2.1 
language-tcl 0.1.2 
latex 0.50.2 
linter 2.3.1 
linter-flake8 2.4.0 
linter-ui-default 1.8.1 
minimap 4.29.9 
multi-cursor 3.0.0 
script 3.26.0 
split-diff 1.6.1 
teletype 0.13.4 
```

**Comment by tomato-300yen** [comment]
I got the same issue...


[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.4
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.14.1


### Stack Trace

Uncaught Error: Cannot find module '/Users/uu/.atom/packages/Hydrogen/node_modules/@nteract/mathjax/lib/index.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:248

Error: Cannot find module '/Users/uu/.atom/packages/Hydrogen/node_modules/@nteract/mathjax/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:13:30)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/markdown-render.js:30:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:6:43)
    at /packages/Hydrogen/node_modules/@nteract/markdown/lib/index.js:11:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:13:36)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/markdown.js:27:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:11:18)
    at /packages/Hydrogen/node_modules/@nteract/outputs/lib/components/media/index.js:20:3)
```

### Commands

```
  2x -5:44.6.0 core:confirm (input.hidden-input)
  2x -5:40 find-and-replace:show-previous (input.hidden-input)
  3x -5:37 core:confirm (input.hidden-input)
 10x -5:20.9.0 core:backspace (input.hidden-input)
     -4:41 core:move-right (input.hidden-input)
  5x -4:40.4.0 core:backspace (input.hidden-input)
  3x -4:38.9.0 core:move-up (input.hidden-input)
  2x -4:36.3.0 editor:delete-to-beginning-of-line (input.hidden-input)
  3x -4:34.2.0 core:move-up (input.hidden-input)
  2x -4:32.5.0 core:move-down (input.hidden-input)
     -4:31.6.0 core:move-left (input.hidden-input)
     -4:31.1.0 core:move-right (input.hidden-input)
     -4:30.9.0 core:move-up (input.hidden-input)
 38x -4:30.7.0 core:move-right (input.hidden-input)
  7x -4:28.1.0 core:backspace (input.hidden-input)
     -4:25.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
autocomplete-paths 2.12.2 
autocomplete-python 1.16.0 
file-icons 2.1.41 
git-log 0.4.1 
highlight-selected 0.17.0 
Hydrogen 2.14.1 
kite 0.184.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
platformio-ide-terminal 2.10.0 
```

**Comment by matthew-brett** [comment]
See also gh-1944, gh-1946.

I had the same problem with a [fresh install](https://gist.github.com/matthew-brett/4c5fa31f8ddd371655e9dc39fbfb8299/296650f4a8b3275da51653e7d154a6ce4af1a56e) on my new desktop.   I have a working installation on my laptop, with identical package specification to that on the desktop, checked via diff of `atom list`, and the same Atom version, checked with `atom --version`.

I can confirm that the folder `packages/Hydrogen/node_modules/@nteract/mathjax/lib` is missing in my desktop installation.  Copying the `lib` folder from the laptop, to the same location on the desktop, fixed the problem.

**Comment by lecondon** [comment]
Thanks for the links @matthew-brett I was able to get my problem fixed by installing an older version of Hydrogen 2.8.0

**Comment by masx14** [comment]
Installing version 2.8.0 did help me for now, but still if I update to 2.14.1 the installation breaks and I have to reinstall version 2.8.0

**Comment by AverageComet250** [comment]
Hey I have the issue that atom doesn't let me use the plugin if it's not updated. Anyone know a solution?

**Comment by tomato-300yen** [comment]
Solution to these issues. Enjoy your Hydrogen!

https://github.com/tomato-300yen/mathjax_lib_for_hydrogen

**Comment by AverageComet250** [comment]
HUGE thanks, I am really looking forwards to being able to use hydrogen

**Comment by mattgebert** [comment]
I have copied the lib folder from @tomato-300yen, because I was missing it with mathjax, but I'm still receiving the stack error trace, because it seems to also be missin in "ansi-to-react".

Can someone post the lib folder for this like @tomato-300yen did?

<details><summary>Click for stack trace</summary>

`Cannot find module 'C:\Users\Matt\.atom\packages\Hydrogen\node_modules\ansi-to-react\lib\index.js'. Please verify that the package.json has a valid "main" entry`

Stack Trace:
```Error: Cannot find module 'C:\Users\Matt\.atom\packages\Hydrogen\node_modules\ansi-to-react\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:155434)
    at Module.require (file:///C:/Users/Matt/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (C:\Users\Matt\.atom\packages\Hydrogen\node_modules\@nteract\outputs\lib\components\kernel-output-error.js:13:41)
    at Object.<anonymous> (C:\Users\Matt\.atom\packages\Hydrogen\node_modules\@nteract\outputs\lib\components\kernel-output-error.js:44:3)
    at Module.get_Module._compile (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/Matt/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (C:\Users\Matt\.atom\packages\Hydrogen\node_modules\@nteract\outputs\lib\index.js:14:29)
    at Object.<anonymous> (C:\Users\Matt\.atom\packages\Hydrogen\node_modules\@nteract\outputs\lib\index.js:27:3)
    at Module.get_Module._compile (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/Matt/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/Matt/.atom/packages/Hydrogen/lib/components/result-view/display.js:5:38)
    at Object.<anonymous> (file:///C:/Users/Matt/.atom/packages/Hydrogen/lib/components/result-view/display.js:82:23)
    at Module.get_Module._compile (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:147450)
    at Object.value [as .js] (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///C:/Users/Matt/AppData/Local/atom/app-1.47.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\Matt\AppData\Local\atom\app-1.47.0\resources\app\static\<embedded>:11:146766)
    at Object.<anonymous> (file:///C:/Users/Matt/.atom/packages/Hydrogen/lib/store/output.js:8:25)
    at Object.<anonymous> (file:///C:/Users/Matt/.atom/packages/Hydrogen/lib/store/output.js:62:33)
```
</details>

**Comment by tomato-300yen** [comment]
@mattgebert Hi, this is ansi_toreact lib folder(^^)
https://github.com/tomato-300yen/ansi_to_react_lib_for_hydrogen

**Comment by larigitusr** [comment]
Thank you very much for the solution! It saved my day!

**Comment by AverageComet250** [comment]
I verymuch think this issue should be pinned and closed, as this thread contains a solution to the problem, and this problem seems quite common

**Comment by mattgebert** [comment]
Yep perfect. All problems on my end solved with the ansi_to_react lib folder also being included. Thanks @tomato-300yen!

**Comment by matthew-brett** [comment]
I dont think the issue should be closed - the goal must be that a Hydrogen install should work correctly without these fixes. 

Given that the installation *of the same exact version of Hydrogen* worked correctly a few weeks ago, on the same Atom version and OS, I wonder whether this could be some interaction with the Atom install machinery.

**Comment by AverageComet250** [comment]
Possibly, but I'm not I don't know how atom works on the inside. I only know basic html and css, plus lots of python. I'm also going to point ihis issue to the issue I accidently created on this same subject know

**Comment by gsidorov** [comment]
Wow I was very happy because I am not getting the initial error and looks like now Hydrogen is working, but now I am getting another type of error:

Python 3

Traceback (most recent call last): File "C:\Users\aicrypto\anaconda3\lib\runpy.py", line 193, in _run_module_as_main "main", mod_spec) File "C:\Users\aicrypto\anaconda3\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "C:\Users\aicrypto\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "C:\Users\aicrypto\anaconda3\lib\site-packages\ipykernel__init__.py", line 2, in from .connect import File "C:\Users\aicrypto\anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in import jupyter_client File "C:\Users\aicrypto\anaconda3\lib\site-packages\jupyter_client__init__.py", line 4, in from .connect import File "C:\Users\aicrypto\anaconda3\lib\site-packages\jupyter_client\connect.py", line 24, in import zmq File "C:\Users\aicrypto\anaconda3\lib\site-packages\zmq__init__.py", line 47, in from zmq import backend File "C:\Users\aicrypto\anaconda3\lib\site-packages\zmq\backend__init__.py", line 40, in reraise(*exc_info) File "C:\Users\aicrypto\anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise raise value File "C:\Users\aicrypto\anaconda3\lib\site-packages\zmq\backend__init__.py", line 27, in _ns = select_backend(first) File "C:\Users\aicrypto\anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend mod = import(name, fromlist=public_api) File "C:\Users\aicrypto\anaconda3\lib\site-packages\zmq\backend\cython__init__.py", line 6, in from . import (constants, error, message, context, ImportError: DLL load failed: The specified module could not be found.

**Comment by fdkssdks** [comment]
> Solution to these issues. Enjoy your Hydrogen!
> 
> https://github.com/tomato-300yen/mathjax_lib_for_hydrogen

Hello, I don't have the folder mathjax_lib but I have mathjax-electron. I copied the lin folder there and I still have the same error 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Ubuntu 18.04.4
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.8.0


### Stack Trace

Failed to activate the Hydrogen package

```
At Unexpected token {

SyntaxError: Unexpected token {
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/kernelspecs/lib/traverse.js:1:167)
    at /packages/Hydrogen/node_modules/kernelspecs/lib/traverse.js:106:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/node_modules/kernelspecs/index.js:1:173)
    at /packages/Hydrogen/node_modules/kernelspecs/index.js:11:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/Hydrogen/lib/kernel-manager.js:3:23)
    at /packages/Hydrogen/lib/kernel-manager.js:179:35)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
```

### Commands

```
     -2:08.5.0 hydrogen:run (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
autocomplete-python 1.16.0 
file-icons 2.1.41 
Hydrogen 2.8.0 
minimap 4.29.9 
python-autopep8 0.1.3 
script 3.26.0 
```

**Comment by mattgebert** [comment]
@fdkssdks I believe I had the same issue as you on my laptop. The solution was that you needed to rebuild Hydrogen first for the new version of Atom, because it was incompatible, then follow the same procedures as above. Not sure if you get some prompt to rebuild incompatible packages?

**Comment by fdkssdks** [comment]
> @fdkssdks I believe I had the same issue as you on my laptop. The solution was that you needed to rebuild Hydrogen first for the new version of Atom, because it was incompatible, then follow the same procedures as above. Not sure if you get some prompt to rebuild incompatible packages?

I will rebuild and report back and I got the error prompt asking to update the packages but not rebuild.

**Comment by rmaues** [comment]
I solve my problem just installing Hydrogen 2.9.

**Comment by Oberonhive** [comment]
Same issue repeated on 2.14.3 version. Can't found another file ~\.atom\packages\Hydrogen\node_modules\@nteract\markdown\lib\index.js

**Comment by ljburtz** [comment]
had the same issue, came here, then upgraded to 2.14.14
FIXED!

**Comment by captainsafia** [comment]
Hello everyone! This issue originally occurred because the @nteract/mathjax package was shipped with some missing assets. The issue was resolved in a prior release so this should no longer be a problem.

I'll close this issue for now but please re-open if it happens again.
